### ISSUE TITLE
an error code in Player.Quests.cs

### ISSUE THREAD

**Issue by leewheel** [DeKaDeNcE/WoWCore#7]
![image](https://github.com/DeKaDeNcE/WoWCore/assets/30166672/70cb1648-3af8-4c4a-88be-075426f7dc6d)
QuestFlags.PlayerCastOnComplete -> QuestFlags.PlayerCastComplete  is that right?

**Comment by ipro4911** [comment]
can you explain futher?

**Comment by leewheel** [comment]
What I mean is that there is a code in the code player.quest that is QuestFlags.PlayerCastOnComplete is reporting an error (QuestFlags does not contain the definition of PlayerCastOnComplete). After changing it to QuestFlags.PlayerCastComplete, it will not report an error. Is this correct?

**Comment by leewheel** [comment]
![image](https://github.com/DeKaDeNcE/WoWCore/assets/30166672/1a41aeff-26f2-41e7-a3dd-06cca40f50bc)

**Comment by ipro4911** [comment]
its normal leave it ther i suppose

**Comment by ipro4911** [comment]
Like dont modify it the definition if it doesnt exist

**Comment by leewheel** [comment]
OK！

**Comment by ZaDarkSide** [comment]
Clone again the repo this issue should be fixed.
